// action-types.js
export const EXPORT_CONTACTS_REQUEST = 'EXPORT_CONTACTS_REQUEST';
export const EXPORT_CONTACTS_SUCCESS = 'EXPORT_CONTACTS_SUCCESS';
export const EXPORT_CONTACTS_FAILURE = 'EXPORT_CONTACTS_FAILURE';
